Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y iputils-ping avahi-daemon libnss-mdns unzip \
        openjdk-17-jdk-headless
  SHELL


  config.vm.define "db" do |db|
    db.vm.box = "generic/ubuntu2204"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.11"

    db.vm.network "forwarded_port", guest: 8082, host: 8082
    db.vm.network "forwarded_port", guest: 9092, host: 9092

    db.vm.provision "shell", inline: <<-SHELL
      wget https://repo1.maven.org/maven2/com/h2database/h2/2.2.224/h2-2.2.224.jar
    SHELL

    db.vm.provision "shell", :run => 'always', inline: <<-SHELL
      java -cp ./h2*.jar org.h2.tools.Server -web -webAllowOthers -tcp -tcpAllowOthers -ifNotExists > ~/out.txt &
    SHELL
  end


  config.vm.define "web" do |web|
    web.vm.box = "generic/ubuntu2204"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.56.10"

    web.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    web.vm.network "forwarded_port", guest: 8080, host: 8080

    #web.vm.provision "shell", inline: <<-SHELL, privileged: false
      #wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.23/bin/apache-tomcat-10.1.23.tar.gz

      #sudo tar xzvf apache-tomcat-10*tar.gz -C .

      #sudo chown -R vagrant:vagrant apache-tomcat-10*

      #sudo chmod -R u+x apache-tomcat-10*
       #SHELL

    #web.vm.provision "shell", :run => 'always', inline: <<-SHELL
       #./apache-tomcat-10*/bin/startup.sh
    #SHELL

    web.vm.provision "shell", inline: <<-SHELL, privileged: false
      git clone https://github.com/hugosousa1231830/devops-23-24-JPE-PSM-1231830.git
      cd devops-23-24-JPE-PSM-1231830/ca2/part2/react-and-spring-data-rest-basic
      chmod u+x gradlew
      ./gradlew clean build
      ./gradlew bootRun

      #sudo cp ./build/libs/react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.war ~/apache-tomcat-10*/webapps/

    SHELL
  end
end
